# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fa571c3538f5fd089f20c344aa8c906ebf7b2d9722477c3b0b74e99a0888a3466375d5f920a5c545cae62a2667266d74751f78b43425d474e5e91bab0bbe9619

test:
  secret_key_base: 95b5007cbf97119151ec83c5993d62b15d36b3536cb560a0856e51cd2f689a7b04b2ed1a198967ce8d0e4a5adfd7ada028c8e243fd9baccc011b45d6dd207ead

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
